### ISSUE TITLE
Призраки!

### ISSUE THREAD

**Issue by Archemagus** [animusdev/Wonderwork#101]
Анализ воздуха не работает!
Так же было бы не плохо впилить просмотр консолей, или хотя бы взаимодействие для админов, ибо очень трудно понять почему "СМЕС не работает" или "как настраивать сингулярность" и т.д.

**Comment by OdSt** [comment]
Будет-будет. Все знаем.

**Comment by OdSt** [comment]
Решена проблема с анализом воздуха. Остальное уже есть в реквесте по призракам.
