### ISSUE TITLE
REJUVINATE вызывает подозрения.

### ISSUE THREAD

**Issue by HAKCA** [animusdev/Wonderwork#16]
Через контекстное меню хилл робит, но при использовании через Player Panel выдаёт ошибку. Ранг: Trial Admin
Error: You do not have sufficient rights to do that. You require one of the following flags: +REJUVINATE.

**Comment by OdSt** [comment]
Ну да, работает через жопу. Не помню, баг это или фича

**Comment by OdSt** [comment]
В общем, решено тем, что были выданы прав больше.
