### ISSUE TITLE
Суицид

### ISSUE THREAD

**Issue by Cyrpet** [animusdev/Wonderwork#18]
Киборг может совершать суицид(когда людей просит сообщить в 'АХелп'). 

Но он не получает урон.

**Comment by OdSt** [comment]
Подробнее поясни ситуацию, при каких обстоятельствах.

**Comment by Cyrpet** [comment]
Обычное тело киборга. Suicide в командную строку и-и-и... "{Username} is powering down...", - но ничего не происходит, кроме текста. Ни урона. Ни изменения 'осмотра'.

**Comment by OdSt** [comment]
А, о, спасибо. Все, ждите в ближайших апдейтах

**Comment by OdSt** [comment]
Посмотрел. Это просто эмоут. Все так и должно работать.
