### ISSUE TITLE
Металлодетекторы

### ISSUE THREAD

**Issue by Archemagus** [animusdev/Wonderwork#2]
1. По неизвестной причине, эти чудотворцы игнорируют содержимое сумок, и прочего инвентаря игрока, при проверке, что не порядок.
2. Если она все же найдет у человека оружие (выходит чтоб спалиться надо в руках нести, ну или на поясе) она станет звенеть каждый раз, когда человек проходит через детектор, даже если он уже избавился от оружия. Сбрасывается если пройти через детектор без карты. Но тогда он успешно навесит тебе аррест на голову. По идее, аррест лучше вешать сразу при первом проходе с оружием.
3. Ну есть два режима работы: игнорировать персонал и СБ, или проверять всех. Переключается карточкой любого человека. Лучше сделать другие два режима: всех сканировать, игнорить СБ и глав. Переключение между режимами тоже сделать по картам СБ и глав.
4. Не знаю что лучше кидать для удобства, но так искать быстрее " /obj/machinery/metaldetector "

**Comment by OdSt** [comment]
Спасибо. Зафиксим
