### ISSUE TITLE
Генерация картинок

### ISSUE THREAD

**Issue by Cyrpet** [animusdev/Wonderwork#28]
1.У всех игроков, в 'Записях Безопасности'(Security Records):

 
1.1. _Отсутствуют_ ладони (на первом виде).

1.2. Имеют ладонь, _покрытую кровью_ (на втором виде).

![screenshot_1](https://user-images.githubusercontent.com/18487565/31316296-3fc3b90c-ac33-11e7-918c-591ca04b6e82.png)

2. Следующие роли имеют _униформу_ обычного ассистента:

2.1. Клоун:

![screenshot_2](https://user-images.githubusercontent.com/18487565/31316369-812dc698-ac34-11e7-81a5-b8b5ea4e3d4c.png)

2.2. Психолог:

![screenshot_3](https://user-images.githubusercontent.com/18487565/31316393-ea7ff9c2-ac34-11e7-930d-1b418ca42782.png)

Могу предположить, что множество _'кастомных'_ работ будут иметь, так же, одежду _ассистента_.

**Comment by OdSt** [comment]
Это было бы логично, если бы они в лобби имели ту же картинку. В принципе там просто идет подгрузка этих пикч из ресурсов. Скорее всего там есть два списка одежды, и как раз во втором баги. Спасибо.

**Comment by OdSt** [comment]
Так, второй пункт пофикшен

**Comment by OdSt** [comment]
Решено
