### ISSUE TITLE
Недоклонер

### ISSUE THREAD

**Issue by Archemagus** [animusdev/Wonderwork#3]
1) Wonderwork/code/WorkInProgress/gemini/humancloner.dm
2) При касании рукой выставляет cloning на 150 и запускает process() который видимо должен отсчитывать cloning до нуля, но выполняется единожды
3) Рад, что откопал его на гитхабе сам, видно что не до делано, но тогда лучше убрать его пока с карты, или хотя бы не ЦК z-уровней
4) Нельзя прикрутить к полу обратно.

**Comment by OdSt** [comment]
За прикручивание спасибо. В остальном да, нужно переписать.

**Comment by OdSt** [comment]
Починено
