### ISSUE TITLE
Криослиперы

### ISSUE THREAD

**Issue by PrimeTed** [animusdev/Wonderwork#31]
Дабы избежать хуйни с респавнами, следует ввести криослиперы. Удобно, полезно, практично.

**Comment by ucnaHez** [comment]
Фуфуфу, зачем нам эта убогая хрень извращенных бейских аутистов? Хочешь выйти из игры - иди в дормы, чай, основное их предназначение (а не ЕРП). Обворуют? Так имеют право, имеешь важные вещи - оставь в кабинете.

Дормы - вообще вотчина генок (которые закусывают апатиками) и сбежавших с тюрчки (которые разживаются барахлом), не надо отнимать у них это.

**Comment by OdSt** [comment]
Доводы испанца котируются.
