### ISSUE TITLE
Доступ

### ISSUE THREAD

**Issue by Cyrpet** [animusdev/Wonderwork#34]
У _обычных учёных_ нет доступа к тех. туннелям.

**Comment by OdSt** [comment]
Доступ есть только в техи, вокруг РнД. И им он и не нужен, если так прикинуть. Чай не вайт.

**Comment by Cyrpet** [comment]
У них нет доступа и в тех. туннели около РнД.

**Comment by Cyrpet** [comment]
Это оставляет учёным лишь один способ покинуть РнД(самостоятельно).

**Comment by OdSt** [comment]
Хм. Гляну. Вообще выход в техи у ксенобиологии и еще кое-где был
