### ISSUE TITLE
Виртуальная Реальность

### ISSUE THREAD

**Issue by Archemagus** [animusdev/Wonderwork#4]
1) Wonderwork/code/WorkInProgress/facepunch/arena/vrpod.dm
2) Все бы ничего, тема классная, но только выйти из ВР можно 3 способами: получить ЭМИ по устройству, или, если его кто то ручками раздолбит, ну и на крайняк - прилететь из "вымышленного мира" и самому себя достать из машинки. Можно добавить виртуальному игроку проц go_out() ?
3) Смерть игрока ничего не дает, просто сидишь в трупе. Убивать оригинал не пробовал, но не думаю, что смысл будет.
4) Когда тестил, прыгал игроком на свое оригинальное тело, меня почему то автоматом гибало и кидало в тело, и только тогда можно ручками вылезти из этого ящика.
5) Тоже, если все грустно - можно просто убрать с карты.

**Comment by OdSt** [comment]
Как можно убегать с карты? В смысле гостом?
В остальном да, костыли-велосипеды. Посмотрю, чем можно сделать с выходом.

**Comment by Archemagus** [comment]
По поводу убегать с карты: суть в том, что есть верб eject() который может сделать только тот, кто находится внутри. По этому как бы и писал что самому себя найти и достать. Нет гостом этого сделать нельзя, и сбежать из ВР тоже нельзя

**Comment by OdSt** [comment]
В общем, немного починил ситуацию.
4 пункт как раз против сбегающих из VR
