### ISSUE TITLE
Диктофон

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/Wonderwork#40]
Нормальный диктофон, который пишет не пять минут (возможно уже есть) и говорит прямо от лица записанного, то есть "John Ballon says, "Хуй"", а не "recorder says, "John Ballon says, "Хуй""".

С этим диктофоном можно обманывать людей, притворяться, что ты есть, записывать дистанционно управляемые речи, положив диктофон под интеркомом и прикрепив сигналлер и многое другое

**Comment by OdSt** [comment]
Посмотрю.

**Comment by OdSt** [comment]
Будет запилено вместе с локализацией
