### ISSUE TITLE
Баррикада

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/Wonderwork#44]
Только что затолкал обезьянку на баррикаду, все остальное вроде не пропускает.

**Comment by OdSt** [comment]
Она и так умеет ходить сквозь. Как и другие мобы

**Comment by ucnaHez** [comment]
С какого-то? Люди не ходят. Баррикада, которая деревянная - это нихуя не проходимая хрень, это же как стена из досок. Это вам не стол.

**Comment by OdSt** [comment]
Посмотрел десяток билдов - везде мобы с флагом хождения по столам могут ходить сквозь нее.

**Comment by OdSt** [comment]
В общем, нужно запретить проход или нет?

**Comment by OdSt** [comment]
В общем, если надо - верну назад.
