### ISSUE TITLE
Гостевые пропуска

### ISSUE THREAD

**Issue by Archemagus** [animusdev/Wonderwork#5]
1) /obj/machinery/computer/guestpass
2) Если в терминал положить карточку или пропуск, можно ее протолкнуть еще одной картой (пихаем новую - старая исчезает). Очень хорошая фича для сжирания просроченных пропусков. Но к сожалению карточки она тоже глотает, и персонал оказывается заперт в своем отсеке без id.

**Comment by OdSt** [comment]
Починено
