### ISSUE TITLE
Психолог

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/Wonderwork#51]
Далеко и надолго, зачем оно вообще в профах?

**Comment by Cyrpet** [comment]
"Почему эта профессия Вам кажется не нужной?"

**Comment by ucnaHez** [comment]
Ассистенты нужны не для "отыгрывания", а для того, чтобы учиться и помогать профессионалам, а психолог нафиг не нужен. Есть бармен - психолог, есть капеллан - психолог, есть, в конце-концов, простой врач, который выслушает твои сны и пропишет таблетос майндбрейкера - хватит.

**Comment by Cyrpet** [comment]
Вероятно, он нужен, чтобы те, у кого 'проблемы со сном' не мешались врачам, которые спасают жизни.

И я ни разу не видел, чтобы ассистенты брались теми, кто только начинает обучатся ролью, которую он выбрал. Но находил игроков, которые уже имели не маленький опыт за роль, которой они хотят 'обучиться'.

**Comment by OdSt** [comment]
Столько РП пропадает с пропажей психулугов

**Comment by ucnaHez** [comment]
Но бармен и психиатр как раз НУЖНЫ для психологической разгрузки. Или ты думаешь, что на станцию прислали СВЯЩЕННИКА чтобы от культа ее защищать? Только помощь экипажу.
