### ISSUE TITLE
Металлодетекторы

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/Wonderwork#58]
Конечно, очень хороши, но расставлять везде включенными - фу. СБшники хотят - пусть таскают и ставят, а делать их работу и ставить оные везде - фу.

**Comment by Archemagus** [comment]
Ммм. Сделать металодетекторы собираемыми в РнД? Раздатчик металодетекторов у СБшников? Ибо со всей станции их сейчас довольно много наберется. Плюсь расположение у них: прибытие, отбытие, мостик и бриг. Считаю, что вполне нормально и сбалансировано - типа I/O + secure zone. Ну и если вообще сильно заебываться, то их можно сделать хакабельными, добавить проводки там,  и как фичу - вариант взлома, при котором пушки просто примагничиваются к рамке и персонажу надо будет их выбросить, или отключить детектор, чтоб сдвинуться.

**Comment by OdSt** [comment]
Чет имбалансно. Можно просто их на карте выключенными ставить

**Comment by ucnaHez** [comment]
Просто поставить штуки четыре в бриг вместе с флешерами и пусть стоят.

нет ничего сбалансированного в том, что СБшнику надо один раз кликнуть мышкой и пушки на шатол не пронести.

**Comment by OdSt** [comment]
Всегда можно через окно. Опять же, сейчас быть тритором максимально легко - спиздил че-то, никто внимания вообще не обращает.

**Comment by ucnaHez** [comment]
Ну, тут мешает тот факт, что заданий много, и пара из них ассасинейт.

И, да, неужели ты думаешь, что офицеры настолько овощи, что не заметят парня, лезущего через окно?

**Comment by OdSt** [comment]
Офицеры - былинные овощи. К тому же часто иначе на шаттл пробраться невозможно

**Comment by OdSt** [comment]
В общем, сделал раздатчик этого говна. Есть в бриге.
