### ISSUE TITLE
Синтезатор материи

### ISSUE THREAD

**Issue by Archemagus** [animusdev/Wonderwork#6]
1) /obj/item/device/material_synth/adv
2) Гениальнейшее устройство, которое позволяет сканировать ресурсы и штамповать их из неоткуда ( давно мечтал о подобном)
3) Собственно загрузил ее до придела, и выяснил, что она не тратит заряды на клепание. Дисбаланс.
4) Не продвинутый синтезатор не пробовал, и начал использование сразу с клепание кусков плазмы.

**Comment by OdSt** [comment]
Хорошо, посмотрю, помоему это фича. Если так, докину на уровень повыше
