### ISSUE TITLE
Текст

### ISSUE THREAD

**Issue by Cyrpet** [animusdev/Wonderwork#63]
Включаю возможность видеть весь текст и 'эмоуты' с мира:
> As a ghost, you will now see all emotes in the world.
> As a ghost, you will now see all speech in the world.

Проверяешь _'Настройки персонажа'_:

> Ghost ears: Nearest  Creatures
Ghost sight: Nearest Creatures

И наоборот.

**Comment by OdSt** [comment]
Не совсем понял о чем речь

**Comment by Cyrpet** [comment]
Текст не совпадает с выставленными настройками.

**Comment by OdSt** [comment]
А где? В настройках? Окей.

**Comment by OdSt** [comment]
Решено
