### ISSUE TITLE
Револьвер детектива

### ISSUE THREAD

**Issue by Archemagus** [animusdev/Wonderwork#64]
Если этот хуй назовет ствол кирилицей, а педаль попробует просмотреть переменные, то ее(педаль) сука выкидывает с сервера к хуям

**Comment by ucnaHez** [comment]
А вот не лазь в ВВ!

**Comment by OdSt** [comment]
Проблема скорее всего в том, что VV принимает в качестве названия строго ASCII а вводить можно и кириллицей

**Comment by Archemagus** [comment]
Ну так проще узнать, кто из него стрелял через ВВ.

**Comment by OdSt** [comment]
Решено
