### ISSUE TITLE
Нехватка спрайтов?

### ISSUE THREAD

**Issue by Archemagus** [animusdev/Wonderwork#66]
Думаю стоит оставить открытым и докидывать диковинки со станции.

![default](https://user-images.githubusercontent.com/32466328/31358696-57d1db4c-ad4f-11e7-8864-f9f496646327.PNG)

**Comment by Archemagus** [comment]
Воть ищо
![image](https://user-images.githubusercontent.com/32466328/31387115-e3102cb8-add1-11e7-8294-e15ba1b3dace.png)

**Comment by OdSt** [comment]
Это фича

**Comment by OdSt** [comment]
В общем, на каждый проебаный спрайт создавайте реквест, пожалуйста. Фиксы пофикшены.
