### ISSUE TITLE
Контейнер

### ISSUE THREAD

**Issue by Cyrpet** [animusdev/Wonderwork#67]
Наполняя _человеческое тело_ ингредиентами можно сделать _сыр_ и _тофу_, которое появится прямо на полу.

**Comment by OdSt** [comment]
фича

**Comment by Cyrpet** [comment]
Появление столь большого сыра, тофу из тела, при этом не имея побочных эффектов(к примеру, 'окси-урон'), - странно.

**Comment by OdSt** [comment]
Ну окей, понял намек

**Comment by ucnaHez** [comment]
Вы чо, это же фича из фич.

И сыр в человеке, и трик в человеке, я даже не знал, что мрази на новобилдах ее занерфали.

**Comment by OdSt** [comment]
Нет, суть в том, чтобы высирание сыра происходило с какими-то эффектами.

**Comment by ucnaHez** [comment]
Там же эпичное бульканье

**Comment by OdSt** [comment]
Не знаю. Если ничего не придумаете, закрою.

**Comment by OdSt** [comment]
Ничего не придумано, пилим дальше
