### ISSUE TITLE
Консольки

### ISSUE THREAD

**Issue by Archemagus** [animusdev/Wonderwork#7]
1) /obj/structure/computer3frame
2) Обычный алгоритм построения компьютерной консоли: из метала сделать корпус, прикрутить его к полу, вставить нужную плату... И прибыли. Так как при установке платы спрайтик меняется на несуществующий, консоль внезапно исчезает с поля зрения, прикрутить отверткой нельзя, ибо нужен клик по спрайту.
3) Нет alt+click по турфу, как например на Белом, это могло бы помочь не только по игре, но и при тесте подобной ереси, ибо заспрайтить все нельзя, а я не посмотрел нет ли проблем при дальнейшей сборке консоли.

**Comment by OdSt** [comment]
пофиксил но надо допроверить

**Comment by OdSt** [comment]
Решено
