### ISSUE TITLE
Squeek!

### ISSUE THREAD

**Issue by Archemagus** [animusdev/Wonderwork#74]
Итак. Внимание вопрос! В раунде 5 мышек, и одна из них ведет светскую беседу. Вопрос: какую из них банить?
Мааам! Верни мышкам порядковый номер!

**Comment by OdSt** [comment]
Банить мышей<

**Comment by ucnaHez** [comment]
Как обладатель пермы за мыша авторитетно заявляю, что это действительно нужно.

**Comment by Archemagus** [comment]
Бля. Протечки ICINIC путем Ghost>Mouse могут сильно доебывать

**Comment by Cyrpet** [comment]
Они умеют говорить на человеческом языке?

**Comment by Archemagus** [comment]
Да! В этом то и проблема.

**Comment by OdSt** [comment]
А, ну боже мой, запилим пиздеж на марсианских диалектах им. Ну или нумерацию

**Comment by OdSt** [comment]
Решено. Вернул нумерацию.
