### ISSUE TITLE
Консоль в хопской

### ISSUE THREAD

**Issue by Mo3goed** [animusdev/Wonderwork#78]
Нельзя сменить профессию через Custom, на капитанской консоли такого не наблюдается.
![image](https://user-images.githubusercontent.com/32720719/31469656-35c05d42-aeeb-11e7-909f-e081035ac8b3.png)

**Comment by OdSt** [comment]
Решено

**Comment by OdSt** [comment]
Она работает, просто при выборе рандомного названия надо не забыть нажать ренейм.
