### ISSUE TITLE
Не выводится сообщение о замыкании игрового автомата ЕМАГом

### ISSUE THREAD

**Issue by Mo3goed** [animusdev/Wonderwork#80]
В отбытии, стоит два прекрасных автомата, игровой(базовый) и Robust Softdrinks, при замыкании питьевого автомата есть такое прекрасное сообщение You short out the product lock on Robust Softdrinks, при взломе игрового автомата, такого сообщения нет.

**Comment by OdSt** [comment]
Окей, поправим

**Comment by OdSt** [comment]
Решено
