### ISSUE TITLE
Убить мышь за предателя

### ISSUE THREAD

**Issue by Mo3goed** [animusdev/Wonderwork#81]
Ну скриншотом все сказано
![image](https://user-images.githubusercontent.com/32720719/31491878-7ef39bd0-af51-11e7-927b-8e4c8dd7ce6d.png)

**Comment by OdSt** [comment]
Элитно же. Впрочем, скорее всего, баг

**Comment by OdSt** [comment]
Вынесено в фичи, после того, как все мыши получили имена
