### ISSUE TITLE
Мусорка 2

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/Wonderwork#84]
Не жалеешь ассистух - пожалей хоть атмостехов с каруселями.

Отмазки уровня "второй вайт не нужен" не принимаются.

**Comment by OdSt** [comment]
Заебали. Запилю специально розовые трубы, которые не дамажат в автомат атмостехам

**Comment by ucnaHez** [comment]
Хоть что-то.

Но лучше бы не страдал нерфянкой и сделал бы нормальные трубы, которые дают экстренный шанс смыться (пусть и с возможностью приехать в сингу), а не отрывают головы.

**Comment by OdSt** [comment]
Нерфянкой страдаешь как раз ты. Пушто как раз снятие дамага - нерф труб. Православные трубы - опасные трубы. Тем более это компенсируется одной фичей, которую я тебе не скажу

**Comment by ucnaHez** [comment]
>нерф

С каких пор отрывающие ноги трубы - православно? Во-первых, это придумали грязные бейцы, во-вторых, это НЕРФАЕТ фичу - убирает у труб транспортную функцию и оставляет только мусорную, а транспортная функция труб ой как широка.

А сам себя в шкаф пихать я не буду, когда меня тритор ебет или только развязался в бриге.

**Comment by OdSt** [comment]
Транспортная функция - это какая же? Отправка невменяемых ололонабигателей в карго? Нет уж, дудки.

**Comment by ucnaHez** [comment]
Да, отправить набежавшего дауна в карго вместо того, чтобы убить (выбираешь второе?), слиться из отсека когда стало жарко, покататься на карусели etc

Странные у тебя о трубах представления. Они всегда транспортные артерии (пусть и вторичные), что придает шарму мусорке в сингу/сжигатель и дает множество интересных комбинаций (не "гриферы с вайта сделают второй вайт", заебали)

**Comment by OdSt** [comment]
Еще раз говорю, что это не нужно ни в каком виде. Никакого "шарма" мусорки нет. Как и этого "духа станции". Не надо оперировать демагогическими понятиями применительно к механу, пожалуйста.
Если атмостехи/СЕ хотят построить безопасную мусорку в сингу - у них будет такая возможность. Для всех остальных - катания по мусорке при каждом чихе (а зная, что гриферы считают это нормальным положением дел) - вредная практика.

**Comment by Archemagus** [comment]
Ну напилить фильтр мобов и сделать выход в бриг. Пусть ололонабигатели ХоСу обьясняют как они и чего они. С побегом от триторов тоже самое. Но это как вариант. И мне хоть больше нравятся ТГ трубы, но все же на Грине пока лучше убивашки.

**Comment by ucnaHez** [comment]
Читаешь жопой.
В последних постах нигде не апеллирую к "духу", а "шарм", если заметил, применяется по отношению к МУСОРКЕ В СИНГУ, потому что сейчас это бесмысленно, ведь нахуя ебаться с трубами, если в сингу полетят не все ездуны, а только мусор?

Ну нету ничего хорошего в ОТСУТСТВИИ ФИЧИ, и прикрываться "гриферами с анимусов" бессмысленно. Какие нахуй гриферы по трубам? По трубам катаются простые люди, которых зажали алиумы, катаются нуфаги (которым, блять, русским языком сказано - стало плохо - смывайся), катаются каргомены, но ГРИФЕРОВ С ВАЙТА ни разу в трубах не видел

**Comment by ucnaHez** [comment]
Никто не говорит, что мусорка - безопасный автобан. Всегда есть некоторый нехилый шанс прилететь в:
- разгерму от бомбы, которая разбила трубу
- карго полное злых и независимых каргоменов/каргоменов культистов
- сингуло
- сжигатель
- веселую игру на выживание с психом
Но это ШАНС, который просто не дает мусорке превратиться в автобан, а не блять стопроцентная вероятность расчленения на куски кровь кишки.

Разница - первый вариант дает возможность съебать из опасной ситуации (НЕ БЛЯТЬ ГРИФЕРАМ С ВАЙТА), но при этом оказаться в еще большей жопе, а второй шанс превращает мусорку из многофункциональной тулзы в гиббер

**Comment by OdSt** [comment]
Ты точно так же можешь прилететь в мусорку с некоторым шансом сломанных рук. Опасная ситуация - повод сьебать, только сьеб не обязательно должен быть безопасным.

**Comment by ucnaHez** [comment]
А что смешного? В большинстве случаев это именно так, никак МУСОРКИ не связаны с ГРИФЕРАМИ (да, с ВАЙТА).

Съеб не должен быть безопасным, и он и не безопасный с нормальными мусорками, а когда после проезжания чуть более чем двух поворотов ты прилетаешь по кускам - лучше водокалия сожрать, и то шансов больше

**Comment by OdSt** [comment]
Сьебать вполне можно в нормальном состоянии. Не из всех отсеков, но из какого-нибудь РнД вполне можно. Мусорка не должна быть средством доставки космонавтиков по станции ни в каком виде. Вопрос закрыт.

**Comment by ucnaHez** [comment]
>не будет потому что потому меня в нуфажестве убил грифер на мусорной трубе

Труба и сейчас СРЕДСТВО ДОСТАВКИ КОСМОНАВТИКОВ, загляни в карго, а вот средством спасения простых людей (не "ГРИФЕРОВ"), как и средством развлечения, она не является

**Comment by OdSt** [comment]
Я еще раз говорю, что ты серьезно ошибаешься на этот счет

**Comment by ucnaHez** [comment]
Нет, ошибаешься ты.

Что, аргументы кончились, кроме "гриферов с вайта по трубам" нет ничего?

**Comment by OdSt** [comment]
Я уже привел тебе аргументы в достаточном количестве. Начиная с того, что мусорка предназначена для сбороса говна и заканчивая тем, что почтовая система предназначена для перемещения грузов, а не мягких тушек космонавтиков. Принять их или нет - выбор за тобой.

**Comment by ucnaHez** [comment]
Она средство доставки вещей, а не камней, поэтому она не может быть настолько жесткой, шо ноги отрывает. Стекло, значит, целым прилетает, шкафам, значит, пофигу, токное оборудование прилетает непокоцанным - а космонавтики по кусочкам.

И, да, если бы она была предназначена для сброса говна - никто бы не закодил залезание в мусорку, пластикфрапсы в карго и так далее. Мусорка всегда позиционировалась (ну, кроме нерфобейцев, но они просто идиоты) как средство сброса мусора И средство передвижения людей.

И вообще, вот те главный аргумент - это хорошая, годная фича, которой сто лет в обед, у которой множество веселых и интересных применений, а ты ее не чинишь просто потому, что "ну она же не для этого предназначена" (отмазки уровня ветра-бейцев (ну откуда в космосе детектив это же нелогично проще нормального криминалиста)). Откуда тебе знать, для чего она предназначена? Ты ее кодил? Вон тебе доводы насчет того, что она для людей тоже кодерами предназначена.

**Comment by ucnaHez** [comment]
И, да, КСТААААТИ.

Кодерами система не предназначалась к такому гибберу в трубах.
Кодеры даже блека, когда делали билд, имели в трубах не такой зверский даамаг (а это, мать вашу, еще те любители острых ощущений). Не знаю, как оно было на оригинальном ТГбее, не найду его сейчас.

А потом, кодеры МИРАКЛА, имея моск, понерфали трубы (они же не второй блек пилят, в конце-концов). Понерфали не совсем в ноль (неизвестно чому), но понерфали как следует.

А потому кодеры кой-какого билд вондерворк трубы пробаффали. Так что не надо мне заливать про "кодеры так хотели"

**Comment by OdSt** [comment]
Надо ли напоминать, что кодеры миракла часто делали сомнительные вещи, как и мапперы миракла, клавшие желтые провода и заимствуя части карты с ТГ. Мы не будем уподобляться кодерам ТГ, которые занерфали мусорку. Единственное - я подумаю над тем, чтобы совсем чуть-чуть снизить урон органам.

**Comment by ucnaHez** [comment]
Про миракл я сказал, чтобы ты не прикрывался "кодеры так считали", ведь ты сам этот нерф запилил.


>кодеры ТГ занерфали мусорку

ты не понимаешь сути слова "занерфали". Занерфали - это в общем смысле не "убрали урон", это "убрали фичу". Например, когда хендтеле запретили пропускать ящики - его занерфали. То же относится и к урону - если добавит урон, например, ХОЖДЕНИЮ В ТЕМНОТЕ (как один раз сделали на блеке) - это тоже нерф, хоть урон и увеличился, потому что это уменьшает возможность ходить в темноте, с которой связаны множество интересных развитий событий.

Смотрим дальше: открываем билдоколлекцию и берем билды, чтобы определить, кто именно трубы понерфал:
- rev4407, всем билдам билд: трубы не дамажат
- староТГ (2012, конечно же): трубы не дамажат
- бей до мержа с рев4407: труб вообще нет
- бей-луна: трубы дамажат (вот он, нерф-то! Они его ДОБАВИЛИ САМИ, чуешь?), но совсем слегка и только на поворотах

Вот исследование. Простое и проверяемое. И по нему каждому блять видно, что это не ТГшники трубы занерфали (убрав дамаг и сделав трубы интересными, ой-ей), а бейцы, самостоятельно его ДОБАВИВ.

**Comment by OdSt** [comment]
У тебя опять выкатываются манипуляции фактами. Нерф в данном случае - не как оно было изначально, ибо так мы дойдем до опенсс, а применительно к конкретному билду в конкретное время. Так что в текущем положении - твое предложение = нерф. Ты можешь сколько угодно упорствовать в аргументации "а вот при тг хуй стоял", но это текущей ситуации не поможет,  Тем более, что данная фича выкачена с конкретными аргументированными целями, и полностью себя оправдывает. Ты можешь быть с нею не согласен, но выпиливать по твоей прихоти ее никто не будет. Тем более, что она контрится одной важной контфичей. Мусорка - не место для дискуссий.

**Comment by ucnaHez** [comment]
Не-не-не, ты не понял.
Это не я пытаюсь аргументировать что-то предыдущими итерациями билдов, это ты утверждаешь, что раньше мусорка робастила, а пидоры-ТГшники ее сломали.

Во всех вариантах твои аргументы ломаются - что в ССке вообще она никогда не робастила, пока бейцы ее не сломали, что в данном конкретном билде она не робастила, пока ты ее не сломал.

Я нигде ничего не говорю про ТГ, это ты сам уже придумал, и, да, в данной нынешней ситуации мое предложение не есть нерф, потому что смотри выше - мое предложение есть разнерф.


Ну и да - ты так и не показал ни на одну цель, ради которой ты понерфал мусорку, кроме "гриферов с вайта" (бредятина) или "ну на билде на котором я раньше играл робастило". Ну не показал ты ни одной "конкретной аргументированной цели", не показал, единственное, что ты говорил - "гриферы по трубам" или "мусорка для этого не предназначена", ни одной нормальной цели выкачено не было.

>контрится

_а если сделать дамаг от хождения в темноте и убирать его если на тебе черная кепка - это тоже норм?_

**Comment by OdSt** [comment]
Я тебе еще раз говорю. Во-первых мусорка не сломана, во-вторых, это ее нормальное состояние. Если ты хочешь дальше играть с гриферами с вайта - иди на вайт. В-третьих - мусорка место определённо небезопасное, что ты не желаешь признавать ни в каком виде, ссылаясь на опыт ТГ, что опять же верх глупости. В-четвертых, мусорка должна иметь определённую "плату" в виде дамага, чтобы быть отбалансированной, учитывая некоторые ее фичи на этом билде. В пятых, ты как специально обошел стороной ферн в своей демагогии о старых билдах. В-пятых, есть пневмотрубы с удобными капсулами на базе ученых как противовес мусорке. В-шестых, я уже предложил тебе вариант с розовыми трубами. И я еще раз повторю, что дамаг с труб никуда не исчезнет.

**Comment by OdSt** [comment]
Ты меня заебал, Я понизил урон в два раза и на этом все.

**Comment by ucnaHez** [comment]
Ну охуеть теперь, отойти нельзя.

>не сломана

Сломана, смотри выше.

>гриферы с вайта

Да как же ты заебал, аргументация уровня трахенов "гриферы с анимуса"

>небезопасное

да хватит долбиться в очи! Я не говорю, что она БЕЗОПАСНОЙ должна быть, я говорю, что она должна быть ЮЗАБЕЛЬНОЙ, и на ТГ я не ссылался, ссылался только ты, крича, что они ее занерфали.
Тут я тебе привел исследование о том, что они как раз не вводили дамаг, и его не было никогда. Какой еще ферн? Нашел, блять, билд, ферн - нихуя не старый билд уровня староТГ, ферн - местная разработочка, основанная на бее, откуда ферн и спиздел нерф мусорок.

>плату

Возможно, но ОПРЕДЕЛЕННАЯ ПЛАТА - это когда приежаешь с десятком-другим брута, как БЫЛО на миракле, а не когда приезжаешь по кускам, как сделал ты.
