### ISSUE TITLE
У РД нет интелкарты

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/Wonderwork#85]

**Comment by OdSt** [comment]
Внимательно осмотрел столы?

**Comment by ucnaHez** [comment]
Вроде да. Даже шкаф глянул.

Возможно сперли ученые

**Comment by OdSt** [comment]
А, нашел ее на мостике.

**Comment by ucnaHez** [comment]
>нашел на мостике

Ясно-понятно, что на мостике. Одна на мостике, одна в хранилище плат и одна у РД, это не взаимозаменяемые вещи.

**Comment by OdSt** [comment]
Две интелкарты на станции - вполне достаточно. Я думал, что ее нет на мостике и она у РД, но нет, она на мостике и этого достаточно.
