### ISSUE TITLE
Двери картами не открыть

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/Wonderwork#86]
Если дверь не открывается на бамп - например, она развинчена или под ферлоком - то при клике по ней картой она не открывается. Это бесит. Когда она развинчена - еще можно завинтить, но уже неудобно, а если под ней фаерлок - то только взламывать

**Comment by OdSt** [comment]
Странно. А когда она под файрлоками? В смысле открытыми?

**Comment by ucnaHez** [comment]
Нет, в смысле фаерлок закрыт, лейер не важен (хотя даже важен, когда фаерлок НАД дверью, его можно открыть и нормально пнуть дверь, а когда фаерлок под - хрен там, альтклика-то нету

**Comment by OdSt** [comment]
Хм. Надо тестировать

**Comment by OdSt** [comment]
Не удалось воспроизвести баг.

**Comment by ucnaHez** [comment]
Зашел, перепроверил - проблема, оказывается, просто в НУ ОЧЕНЬ долгом реагировании дверей. Я тыкаю по двери картой, и она через секунды две открывается, я просто не дожидался такого долгого отклика.
