### ISSUE TITLE
Автомат и емаг

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/Wonderwork#87]
Игровой автомат при проигрыше в емагнутом виде ВЗРЫВАЕТСЯ 1-2-3.

Верните гиб, это не только веселее и честнее - РИСКИ повышаются, но и еще при ЗАСе гиб куда мирнее, чем дырка, которая убьет не только игруна, но еще и всех в коридоре.

**Comment by OdSt** [comment]
Это же фича или баг?

**Comment by ucnaHez** [comment]
Я не знаю, зачем это поменяли, но это явно хуже, чем было.

**Comment by OdSt** [comment]
А, это нерфоклоунство!

**Comment by OdSt** [comment]
Решено
