### ISSUE TITLE
Мусорка 3

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/Wonderwork#93]
Хватит заливать про "сейчас можно доехать но покоцанным", я покатался и единственное, откуда я приехал способным ходить - из КМской. Из роботики в предкрите с переломанными частями тела, из инженерки трупом, причем трупом на полпути, из коридора ботаники (до карго чутька) - трупом, дальше уж тем более. 

Проще гиббер пережить.

**Comment by OdSt** [comment]
Иди нахуй. Билд с фиксами не стоит на сервере
